config/routes.rb
Rails.application.routes.draw do
  get 'pagination/index'
  get 'pagination/pagination'
  get 'pagination/get_articles'
  get 'sessions/new'
  get 'users/new'
  get 'index/index'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :articles do
  resources :users
   collection do
    get 'pagination'
  end
  end
 
  resources :users
  root 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
belongs_to :user
has_many :image
mount_uploader :image, ImageUploader
validates :image, file_size: { less_than: 1.megabytes }
validates :title, presence: true,
                    length: { minimum: 5 }

end

app/models/image.rb
class Image < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
has_many :articles
before_save { self.email = email.downcase }
validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
					has_secure_password
					validates :password, presence: true, length: { minimum: 6 }

def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
 include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 def index
    @articles = Article.paginate(:page =>params[:page], per_page: 2)
	
  end

 def show
    @article = Article.find(params[:id])
  end
def new
@article = Article.new
end
def create 
@article = current_user.articles.build(article_params)
 

 if @article.save
  redirect_to @article
  else
  render 'new'
  end
end
 def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end
private
  def article_params
 params.require(:article).permit(:title, :text, :image, :image_cache)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  @articles = Article.paginate(:page =>params[:page], per_page: 2)
  
  end
end

app/controllers/pagination_controller.rb
class PaginationController < ArticlesController
  def index
  @articles = get_articles

    # total count of pages 
    @page_count = @articles.total_articles
    # url for ajax requests
    @endpoint   = '/articles/pagination'
  end

  def pagination
    render partial: 'articles/index', layout: false, locals: { articles: get_articles }
  end

  def get_articles
   page  = params[:page].present? ? params[:page] : 1
    # per_page is a class variable defined in the Post model class
    articles = articles.paginate(page: page, articles_path: Article.per_page)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
   def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Осуществить вход пользователя и перенаправление на страницу профиля.
   log_in user
      redirect_to user 
   else
        flash[:danger] = 'Invalid email/password combination' # Не совсем верно!
      render 'new'
    end
  end
   def destroy
     log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
    @user = User.find(params[:id])
  end 
 def new
 @user = User.new
  end
   def create
    @user = User.new(user_params)    # Не окончательная реализация!
    if @user.save
	log_in @user
	flash[:success] = "Welcome to the Sample App!"
       redirect_to @user
    else
      render 'new'
    end
  end
   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def log_in(user)
    session[:user_id] = user.id
  end
   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
   def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_index.html.erb
  <% @articles.each do |article| %>
  <table class="table table-striped">
<p>
 <h2> <arttitle>
  <%= article.title %>
	</arttitle></h2>
</p>


   <blockquote>
   <%= link_to(image_tag(article.image.thumb.url, alt: 'Image'), article.image.url, target: '_blank') if article.image? %>
  <%= article.text %>

  



  </blockquote></br>
  
  <% if article.autor == "Admin" %>
  <arttitle style="color:red">
  Автор: <%= article.user.name %>
  <arttitle>
  <% else %>
  <arttitle>
  Автор: <%= article.user.name%>
  <% end %>
  <arttitle>
  </arttitle>

</table>

  <% end %>
 <div style="color:white; padding-left:40%;"> <%= will_paginate @articles %></div>

app/views/articles/_pagination.html.erb
.pagination{
  / inline styles ONLY FOR EXAMPLE
  / PLEASE DO NOT USE THEM
  style='display:none; margin:20px 0; text-align:center;'
  data-pagination-endpoint="#{endpoint}"
  data-pagination-pages="#{page_count}"
  data-pagination-container="#{container}"
}
  = image_tag 'ajax-loader.gif'

app/views/articles/index.html.erb
  <% @articles.each do |article| %>
  <table class="table table-striped">
<p>
 <h1> <arttitle>
  <%= article.title %>
	</arttitle></h1>
</p>

<p>
   <blockquote>
  <%= article.text %>
   <%= link_to 'Далее...', article_path(article) %>
  </blockquote>
  
</p>
<td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
</table>

  <% end %>
  <div class="btn btn-sm blue">
  <%= link_to 'Новая статья', new_article_path %>
  </div>

app/views/articles/new.html.erb
<div class='bg' style="color:white">
<div class="col-md-6 col-md-offset-3" >
<%= bootstrap_form_with scope: :article, url: articles_path, local: true do |f| %>

 <p>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.text_area :text %>
  </p>
  
		

  <p>
    <div style="color:#000"><%= f.submit %></div>
  </p>
  <div>
   
    <%= f.file_field :image %>
	<%= f.hidden_field :image_cache %>
  </div>
  <%= render 'shared/errors', object: @article %>
<% end %>
	
</div>
 </div>

app/views/articles/show.html.erb
<table class="table table-striped">
<p>
 <h1> <arttitle>
  <%= @article.title %>
	</arttitle></h1>
</p>

<p>
   <blockquote>
  <%= @article.text %>
  </blockquote>
  <%= @article.autor %>
</p>
</table>

app/views/index/_articles.html.erb
  <% @articles.each do |article| %>
  <table class="table table-striped">
<p>
 <h1> <arttitle>
  <%= article.title %>
	</arttitle></h1>
</p>

<p>
   <blockquote>
  <%= article.text %>
   <%= link_to 'Далее...', article_path(article) %>
  </blockquote>
  
</p>

</table>
  <% end %>
  <div class="btn btn-sm blue">
  <%= link_to 'Новая статья', new_article_path %>
  </div>

app/views/index/index.html.erb
<div class='bg'>

<a class='logo' href='dsa' ></a></br></br>
<%= render '/articles/index' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    2019 (c)
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Blog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Главная", root_path %></li>
       
        <% if logged_in? %>
           <li><%= link_to "Новая статья", new_article_path %> </li>
         <li><%= link_to current_user.name, current_user %> </li>
     
           <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= render 'layouts/shim' %>
 </head>

  <body>
  <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
   
	
    <%= yield %>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/pagination/_pagination.html.erb
.pagination{
  / inline styles ONLY FOR EXAMPLE
  / PLEASE DO NOT USE THEM
  style='display:none; margin:20px 0; text-align:center;'
  data-pagination-endpoint="#{endpoint}"
  data-pagination-pages="#{page_count}"
  data-pagination-container="#{container}"
}
  = image_tag 'ajax-loader.gif'

app/views/pagination/get_articles.html.erb
<h1>Pagination#get_articles</h1>
<p>Find me in app/views/pagination/get_articles.html.erb</p>

app/views/pagination/index.html.erb
.main-container
  h1.page-header = t 'posts.header'
  
  .posts-list
    = render partial: 'partials/posts', locals: { posts: @posts }

  # 'container' - where we want to load next page of posts
  = render partial: 'partials/pagination', locals: { endpoint: @endpoint, page_count: @page_count, container: '.posts-list' }

app/views/pagination/pagination.html.erb
<h1>Pagination#pagination</h1>
<p>Find me in app/views/pagination/pagination.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h3>Some errors were found:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
	
	
	<h2>Articles</h2>
<% @user.articles.each do |article| %>
  <p>
    <%= article.title %>
  </p>
<% end %>
	
	
  </aside>
</div>